### ISSUE TITLE
eInvalidDwgVersion on OpenForEdit

### ISSUE THREAD

**Issue by sanzoghenzo** [wtertinek/Linq2Acad#11]
This is embarassing.... 😞 
The default value for `GetDwgVersion` uses `Database.LastSavedAsVersion`;
but this property is relative to the current session, so if the database was not saved defaults to 0 (`MC0To0`), which in turn results in the `eInvalidDwgVersion` error.

The right property to use is `Database.OriginalFileSavedByVersion`, that doesn't include the current session.

sending a fix as soon as I get this issue number 😉

**Comment by wtertinek** [comment]
Hi, thanks for raising this issue. To be honest, I didn't test it in AutoCAD and I didn't know that there's a `OriginalFileSavedByVersion`...
