### ISSUE TITLE
NuGet Packages

### ISSUE THREAD

**Issue by sanzoghenzo** [wtertinek/Linq2Acad#13]
Hi there!

It would be wonderful if you can bundle this library as NuGet package!

[This guide](https://www.jamescroft.co.uk/how-to-build-publish-nuget-packages-with-github-actions/) explains how to build and publish a package, but it runs on a ubuntu machine; It should be easy to change the platform.

Let me know what you think!

Happy holidays

**Comment by wtertinek** [comment]
Hi sanzoghenzo,

thanks for opening this issue and thanks for the link. Creating NuGet packages is on top of my todo list for my Christmas holidays. I keep you updated. :)

Happy holidays!

**Comment by wtertinek** [comment]
Hi,

I finally managed to created the NuGet packages. There is a dedicated package for each AutoCAD version, e.g. Linq2Acad-2022. For testing purposes I pushed Linq2Acad-2022, Linq2Acad-2021 and Linq2Acad-2020 to the NuGet-Test server. To receive the packages you have to add https://apiint.nugettest.org/v3/index.json to your package sources in Visual Studio. Furthermore you have to check _Include prereleases_ in the NuGet browser.

The code is available on a new branch caled _release_ and not yet merged into master.

Documentation has been updated and one major breaking change was made (f48f74ede2554ef2c968fe52b03e1ec1f0d956ff).

I'm happy to get some feedback!

**Comment by wtertinek** [comment]
Hi, I just published the packages on nuget.org. The current version is 1.0.0-RC3, so _Include prereleases_ is still needed to find the packages, but it is now available from the standard NuGet server. I thought it would be best to have a "public beta" for another four weeks. If everything goes well, we cann release version 1.0.0 on March 1st.

**Comment by benkoshy** [comment]
Wolfgang, the spoils of victory are yours. well done!

**Comment by sanzoghenzo** [comment]
Sorry for my silence... I just managed to switch to the nuget packages!

It took me almost an hour, I was unaware of the breaking changes you made (`DbObjects` and `ClearValues`) 😅 

I confirm that the 2021 version is working!

**Comment by wtertinek** [comment]
Hi Ben, thanks for your feedback. Good point, I'll add that to the documentation (currently working on documenting the API).

BTW, I published a new RC that contains three more breaking changes (new PaperSpace property 494884238adb4a4521581d7f36dd267ceded7cdf, Add renamed to AddRange, 1a80da801c83de898a01b01f719a487bd47cbc9f, Styles grouped c3c72f7588ffd1b7b3ee22bc44c6a1ad1eb89dcc). I refactored the code and believe that these changes make the API clearer.

**Comment by benkoshy** [comment]
> Hi Ben, thanks for your feedback. Good point, I'll add that to the documentation (currently working on documenting the API).
> 
> BTW, I published a new RC that contains three more breaking changes (new PaperSpace property [4948842](https://github.com/wtertinek/Linq2Acad/commit/494884238adb4a4521581d7f36dd267ceded7cdf), Add renamed to AddRange, [1a80da8](https://github.com/wtertinek/Linq2Acad/commit/1a80da801c83de898a01b01f719a487bd47cbc9f), Styles grouped [c3c72f7](https://github.com/wtertinek/Linq2Acad/commit/c3c72f7588ffd1b7b3ee22bc44c6a1ad1eb89dcc)). I refactored the code and believe that these changes make the API clearer.

That's good idea. Maybe it's best if i document it, seeing i faced the particular problem myself.

**Comment by wtertinek** [comment]
Finally, version 1.0.0 is on NuGet! Thanks for your participation @sanzoghenzo, @benkoshy!
