### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by BKSpurgeon** [wtertinek/Linq2Acad#3]
hello Mr Wolfgang

I'm having some trouble getting your project installed.

When I run your batch file it's saying a warning:

> "Warning	1	There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "AcCoreMgd", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	Linq2Acad"

when i do not run your batch file, i simply insert refernces to the three ObjectArx dlls on my local computer and it compiles ok, but the tests - the tests fail. Because AcadTestRunner is at an internal variable somewhere pointing to my autocad installation folder - which is not yet configured, given the batch file is not run.

any advice much appreciated.

I shall also look closely at your tests - which is probably worth of a blog topic in and of itself. my question was how you managed to test everything given the problems associated with using other dlls and them being called by the autocad program.

rgds

Ben

**Comment by wtertinek** [comment]
Hello Ben, thanks you for raising this issue. The install script is currently not very well implemented, I definitively have to update it. I hope that I'll find some time for that in the next days.

Thanks,
Wolfgang

**Comment by BKSpurgeon** [comment]
Hi mr Wolfgang you needn't fix the install script - just LMK what it's doing. especially the acadTestRunner. how you are running tests with Acad is a big mystery and question (for me at least) would be very interested to get a general overview of what is going on.

rgds

Ben

**Comment by BKSpurgeon** [comment]
hello mr wolfgang any luck on the install script? folks won't be able to use or contribute to your code till it's done. rgds, Ben

**Comment by wtertinek** [comment]
Hi Ben, I think I'll find some time at the weekend. It let you known when I fixed it.

Regards,
Wolfgang

**Comment by BKSpurgeon** [comment]
Mr Wolfgang - i thought of something: if the current database is being used then surely the current transaction can always be obtained (?) : if so we can get rid of the using statement in the client code entirely, because the transaction can be obtained within the containers themselves - because we can always get the reference to the current database? is there a faulty reasoning in there somewhere?

**Comment by BKSpurgeon** [comment]
I was just playing around.

In the client class we'd have to establish a try catch block where we start a transaction, and in the finally statement we would have to dispose the transaction.

And within your helper methods you'd simply have to  retrieve the transaction which was started in the client class.

```c#
            this.db = Application.DocumentManager.MdiActiveDocument.Database;
            this.tr = db.TransactionManager.TopTransaction;
```

that way you would obviate the using statements and since the transaction would be opened and disposed at the stop of the stack, it's basically out of the way.

Furthermore, you could implement your own containers where you could have:

List<BlockReference> etc held in different fields in a particular class.

just some ideas that came to my mind.

...................a second idea i shall probably write on when i've more fully thought it out.

**Comment by wtertinek** [comment]
HI Ben,

I updated the configuration script. It tried to address the architecture missmatch problem you initially posted and removed all references to the x86 architeture. I might have caused your problem. At the moment only "AnyCPU" is supported.

Please try the following: please make a fresh clone of the repository (so we can be sure you have to correct intial state). Then execute Configure.bat in the Configuration directory. You now should be able to compile the solution properly.

FYI:  For the moment I removed the tests from the solution due to the other problem with the AcadTestRunner (which I will address later).

Your other questions are interesting and we should talk about them in another context, as they are not directly related to this issue. I'm thinking of setting up a mailing list. What do you think about that?

Thanks,
Wolfgang

**Comment by BKSpurgeon** [comment]
Excellent Mr Wolfgang, I shall try to make it work laterz tonight.

i have no objection to a mailing list. even better would be the blog where people can see ideas and comment so that - aptly pointed out: it would allow the needs drive the development. the wiki on github would perhaps be ideal? it's like a mailing list but public.

in any case i have started writing up something so it will be more clear as to what i'm talking about and i'll post it to you when finished.

rgds
Ben

**Comment by BKSpurgeon** [comment]
it successfully builds. i added the reference to the 3 dlls from my ObjectARX folder and commented out all the sample code.

great now i can really study this code.
rgds
Ben
