### ISSUE TITLE
Provide Interfaces for Unit Testing

### ISSUE THREAD

**Issue by sanzoghenzo** [wtertinek/Linq2Acad#33]
## Expected Behavior

Hi there, long time since my last request! :wink: 

How do you see the creation of interfaces from the current Linq2Acad classes?

I'm going all in with Dependency Injection for my code, and I would like to use it also with Linq2Acad to be able to do unit testing to my actual code instead of having to do integration testing with AutoCAD every single time (of course it will still be needed, but with unit testing I can quickly make changes knowing that I don't break anything already tested).

## Current Behavior

`AcadDatabase` is a concrete class without interface, and to reach my goal I would have to use the adapter pattern to wrap the class into another one that implements an interface that can be mocked.
If it were only this class it would be easy, but then the work must be repeated for each of the concrete classes of the project.

I know that this solves my wishes only in part, because the underlying AutoCAD library has the same issue, so classes from it still need a wrapper around it; but it would be a good start if what we (you) can control can be used by talking to an interface instead of the implementation

**Comment by CADbloke** [comment]
What you're asking for is an integration test. Try my [CADtest](https://github.com/CADbloke/CADtest) project & see if that does what you're looking for. 
I tried mocking the AutoCAD API once. Once. Hence CADtest.

**Comment by sanzoghenzo** [comment]
Hi @CADbloke,
thanks for the suggestion; I already saw CADtest a while ago, but I admit I never actually tried it, I felt the instructions too cumbersome :sweat_smile:  I will try it soon!

Anyway, integration testing is exactly what I would like to avoid; I understand that it is difficult or even impossible with AutoCAD library, but just having the Linq2Acad library with proper interfaces would help to code respecting the [SOLID principles](https://en.wikipedia.org/wiki/SOLID).

Having a `IAcadDatabase` interface could help implementing compatible classes for other libraries/products, such as Civil 3D (I'm developing something similar for my projects), classes and methods that use the interface as type parameter will be compatible with both, without having to duplicate a single line of code.

**Comment by wtertinek** [comment]
Hi, glad to hear from you again. Very good idea to use dependency injection. But I don't think that what your're asking for will solve the design problem you probably have.

When using dependency injection, it is best to have interfaces that are abstractions of concepts of your domain, not abstractions of technical conecpts. `IAcadDatabase` would be an abstraction of a technical concept. It would be defined within Linq2Acad and this would mean that whatever implementation of that interface you use, the implementation is tightly coulped to Linq2Acad. This is not what you want when using DI, your goal should be to have as little external coupling as possible.

So I would suggest, in case of depenency injection, to not abstract your technical services, but your domain services. Create an application core that is independent of whatever technical infrastructure you are using (and Linq2Acad is technical infrastructure). This application core can then be used with whatever technical infrastructure you want by injecting adapters that connect your appliaction core with a CAD system for instance.

Here is an example: there are things called `Item`s that have a name and a position. We have a service that returns all available items and we have another service that prints the items. The application core does not know about AutoCAD. All AutoCAD stuff is injected into it.

```csharp
// --------------------------------------------------------------------------------------------------------
// This is the application core. It is independend of infrastructure, describes your actual problem domain.
// All your domain logic is here. The application core is what you test with your unit tests.
// This is the core you reuse in different CAD systems.
// ---------------------------------------------------------------------------------------------------------

public class Item
{
  public Item(string name, double[] position)
  {
    Name = name;
    Position = position;
  }

  public string Name { get; }
  
  public double[] Position { get; }
}

public interface IItemProvider : IDisposable
{
  Item[] GetItems();
}

public interface IItemProviderFactory
{
  IITemProvider CreateProvider();
}

public interface IItemPrinter
{
  void Print(Item item);
}

public class Appliciation
{
  private readonly IItemProviderFactory itemProviderFactory;
  private readonly IItemPrinter itemPrinter;
  
  public Application(IItemProviderFactory itemProviderFactory, IItemPrinter itemPrinter)
  {
    this.itemProviderFactory = itemProviderFactory;
    this.itemPrinter = itemPrinter;
  }
  
  public void PrintItems()
  {
    using (var provider = itemProviderFactory.CreateProvider())
    {
      foreach (var item in provider.GetItems())
      {
        itemPrinter.Print(item);
      }
    }
  }
}

// ---------------------------------------------------------------------------------------------------------
// This is the implementation of your AutoCAD infrastructure (the only part where Linq2Acad comes into play)
// Implementations of the interfaces connect your application core with AutoCAD
// ---------------------------------------------------------------------------------------------------------

public class AcadItemProviderAdapter : IItemProvider
{
  private readonly AcadDatabase database;
  
  public ItemProvider()
    => database = AcadDatabase.Active();
  
  public Item[] GetItems()
    => database.ModelSpace
               .OfType<BlockReference>()
               .Select(b => (BlockReference: b, Block: database.Blocks.Elemenet(b.BlockTableRecord)))
               .Select(i => new Item(i.Block.Name, i.Position.ToArray()))
               .ToArray();
  
  public void Dispose()
    => database.Dispose();
}

public class Factory : IItemProviderFactory
{
  public IITemProvider CreateProvider()
    => new AcadItemProviderAdapter();
}

public class AcadPrinter : IItemPrinter
{
  public void PrintItem(Item item)
    => Editor.WriteLine(item.Name);
}

// ---------------------------------------------------------------------------------------------------------
// This is your AutoCAD plugin that creates the final connection between your application core and AutoCAD
// Here you do your integration tests
// ---------------------------------------------------------------------------------------------------------
public class AddIn : IExtensionApplication
{
  private Application application;
  
  public void Initialize()
    => application = new Application(new Factory(), new AcadPrinter()); // Poor man's DI
  
  public void Terminate() { }
  
  [CommandMethid("PrintItems")]
  public void PrintItems()
    => application.PrintItems();
}
```

Hope that helps.

**Comment by sanzoghenzo** [comment]
Thanks @wtertinek , wonderful explanation!

You're right, I was refactoring my existing code in a bottom-up fashion and lost the big picture! I was going in that direction for some parts (I created an adapter for the editor input, and a serilog sink for the output so I can use ILogger), but for others I still haven't abstracted at the right level.

However, I have some code that is made for batch processing, and the database needs to be passed to various jobs. I'm scratching my head figuring out how to hide this without having to write an adapter that wraps the entire class, hence the request. 

This is the gist of what I'm doing:

```cs
interface IBatchJob {
  bool Execute(AcadDatabase db)
}

public class BatchJobExecutor {
  public void Run(IEnumerable<string> files, IEnumerable<IBatchJob> jobs){
    foreach (var file in files) {
      foreach (var job in jobs) {
        using var db = AcadDatabase.Use(file);
        job.Execute(db);
        db.Save();
      }
    }
  }
}
```

Is there a clever way to solve this?

After years of python duck typing, that much verbosity is killing me 🤣

**Comment by wtertinek** [comment]
> After years of python duck typing, that much verbosity is killing me 🤣

:D Haha, can imagine that. Just see the compiler as your friend and keep typing. ;)

The simplest way would be to see the `AcadDatabase` as an implementation detail and push it into an `IBatchJob` implementation. So simply change the argument type from `AcadDatabase` to `string`:

```csharp
interface IBatchJob {
  bool Execute(string fileName)
}

public class BatchJobExecutor {
  public void Run(IEnumerable<string> files, IEnumerable<IBatchJob> jobs) {
    foreach (var file in files) {
      foreach (var job in jobs) {
        job.Execute(file);
      }
    }
  }
}

public class AcadBatchJob : IBatchJob
{
  public bool Execute(string fileName) 
  {
    using var db = AcadDatabase.Use(fileName);

    // Actual job exection goes here

    db.Save();
  }
}
```

**Comment by sanzoghenzo** [comment]
Thanks @wtertinek 
I thought of it, too. I was hoping to avoid repeating I/O calls, especially with nowadays cloud storage clients (Google Drive/OneDrive).
But since I still have to use the executor with more than one job at a time, I can live with that for now!

Thanks again, have a great day!
