### ISSUE TITLE
Issue with links in CodeSamples.MD file

### ISSUE THREAD

**Issue by kdub-nz** [wtertinek/Linq2Acad#35]
## Expected Behavior

links 
Code from [SampleCode.cs](https://github.com/wtertinek/Linq2Acad/blob/master/src/Sources/Linq2Acad.SampleCode.CS/SampleCode.cs). See [SampleCode.vb](https://github.com/wtertinek/Linq2Acad/blob/master/src/Sources/Linq2Acad.SampleCode.VB/SampleCode.vb) for VB.NET samples.

should be valid

## Current Behavior

404 error
The 'wtertinek/Linq2Acad' repository doesn't contain the 'src/Sources/Linq2Acad.SampleCode.CS/SampleCode.cs' path in 'master'.  

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Linq2Acad Version: na
* AutoCAD Version:   na

## Failure Information

na

### Sample Code

na

## Checklist

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [* ] I checked to make sure that this issue has not already been filed
- [* ] I have provided sufficient information for the team

**Comment by wtertinek** [comment]
Thanks @kdub-nz for submitting this bug, thanks @benkoshy for fixing it.
