### ISSUE TITLE
accessing blockreference attribute values?

### ISSUE THREAD

**Issue by benkoshy** [wtertinek/Linq2Acad#4]
Hello Mr Wolfgang

I have a curious problem, which I wasn't sure about how to implement given your library.

I have a block reference and I want to retrieve a particular attribute value from it.

Is there any way that this can be done using your library?

if so pls LMK.

rgds

Ben

```c#        
        private string GetAttributeValue(string tag)
        {
            string attributeValue = "";

            using (var db = AcadDatabase.Active())
            {
                BlockReference en =  db.ModelSpace.Element(id) as BlockReference;
            }
            // How to get to attribute value??

            return attributeValue;
        }
```

**Comment by BKSpurgeon** [comment]
This is the answer which I came up with but I would prefer to use your library: 

```c#
private string GetAttributeValue(string tag)
        {
            string attributeValue = "";

            using (var db = AcadDatabase.Active())
            {
                BlockReference br =  db.ModelSpace.Element(id) as BlockReference;

                AttributeCollection ac = br.AttributeCollection;

                Transaction topTransaction = db.Database.TransactionManager.TopTransaction;

                foreach (ObjectId arId in ac)
                {
                    AttributeReference ar = topTransaction.GetObject(arId, OpenMode.ForRead) as AttributeReference;

                    if (ar.Tag == tag)
                    {
                        attributeValue = ar.TextString;
                    }
                }
                
            }

            return attributeValue;
        }

```

**Comment by wtertinek** [comment]
Hi Ben,

there is not really a way to solve this problem using Linq2Acad. Linq2Acad primarily deals with objects of the main database tables and dictionaries. As AttributeReferences are sub elements of BlockReferences, they are one level too deep in the object hierarchy to be handled by Linq2Acad.

So instead of using Linq2Acad, I would write an extension method in this case. Something like this:

```csharp
public static class BlockReferenceExtensions
{
  public static string GetAttributeValue(this BlockReference br, string tag)
  {
    Func<Transaction, string> getValue = tr =>
                                          {
                                            var attribute = br.AttributeCollection
                                                              .Cast<AttributeReference>()
                                                              .FirstOrDefault(ar => ar.Tag == tag);

                                            return attribute != null ? attribute.TextString : null;
                                          };

    if (br.Database.TransactionManager.TopTransaction != null &&
        !br.Database.TransactionManager.TopTransaction.IsDisposed)
    {
      return getValue(br.Database.TransactionManager.TopTransaction);
    }
    else
    {
      using (var tr = br.Database.TransactionManager.StartTransaction())
      {
        return getValue(tr);
      }
    }
  }
}
```

Then you can use it in conjunction with Linq2Acad:

```csharp
using (var db = AcadDatabase.Active())
{
  var br = db.ModelSpace.Element(id) as BlockReference;
  var value = br.GetAttributeValue("Data");
}
```

Hote this helps,
Wolfgang

**Comment by BKSpurgeon** [comment]
chrs

why not add as such to the class itself? Setting and getting attribute values is a common function?

**Comment by wtertinek** [comment]
Hi Ben,

I first was against adding this to the library because dealing with transactions in extension methods can be problematic. But then I realized that we don't need a transaction to access the attribute references, the same applies to dynamic properties. So I added the extension methods GetValue, SetValue and Contains to AttributeCollection and DynamicBlockReferencePropertyCollection (I hate this long property name).

It is now possible to do something like this:

```csharp
using (var db = AcadDatabase.Active())
{
  var br = db.ModelSpace.Element(id) as BlockReference;

  if (br.AttributeCollection.Contains("Attribute1"))
  {
    var aValue = br.AttributeCollection
                   .GetValue("Attribute1");

    br.AttributeCollection
      .SetValue("Attribute1", "Test");
  }

  if (br.DynamicBlockReferencePropertyCollection.Contains("Property1"))
  {
    var pValue = br.DynamicBlockReferencePropertyCollection
                   .GetValue("Property1");

    br.DynamicBlockReferencePropertyCollection
      .SetValue("Property1", 123);
  }
}
```

I made a new develop branch and pushed the code to it.

Thanks for your comments Ben!

Br,
Wolfgang

**Comment by BKSpurgeon** [comment]
chrs Mr Wolfgang

this is quite interesting. i too thought that we need a transaction to get and set attribute reference values. it seems strange that it does not?


rgds

Ben

**Comment by BKSpurgeon** [comment]
Hi Mr Wolfgang 

I have had another look at the code here:

https://github.com/wtertinek/Linq2Acad/blob/develop/Linq2Acad/Extensions/AttributeCollectionExtensions.cs


It seems that one cannot cast attribute collection elements as AttributeReferences meaning that it looks like a transaction will be needed to open and read them?

I may have made a mistake though.

**Comment by DaSnodgrass** [comment]
I could not get this to work either, so I grabbed the **Database.TransactionManager.TopTransaction**.
The transaction should be provided by the ContainerEnumerableBase class if I understand it correctly.

`
namespace Linq2Acad
{
  public static class AttributeCollectionExtensions
  {
    public static bool ContainsAttribute(this BlockReference br, string tag) => br.AttributeCollection
      .Cast<ObjectId>()
      .Select(id => (AttributeReference)br.Database.TransactionManager.TopTransaction.GetObject(id, OpenMode.ForRead)).Cast<AttributeReference>()
      .Any(ar => ar.Tag.Equals(tag, StringComparison.CurrentCultureIgnoreCase));

    public static bool Contains(this AttributeCollection attributes, string tag)
    {
      return attributes.Cast<ObjectId>().Select(id => id.**Database.TransactionManager.TopTransaction**.GetObject(id, OpenMode.ForRead)).Cast<AttributeReference>()
                       .Any(ar => ar.Tag.Equals(tag, StringComparison.CurrentCultureIgnoreCase));
    }

    public static string GetValue(this AttributeCollection attributes, string tag)
    {
      var attribute = attributes.Cast<ObjectId>().Select(id => id.Database.TransactionManager.TopTransaction.GetObject(id, OpenMode.ForRead)).Cast<AttributeReference>()
                                .FirstOrDefault(ar => ar.Tag.Equals(tag, StringComparison.CurrentCultureIgnoreCase));

      if (attribute == null)
      {
        throw Error.KeyNotFound(tag);
      }
      else
      {
        return attribute.TextString;
      }
    }

    public static void SetValue(this AttributeCollection attributes, string tag, string value)
    {
      var attribute = attributes.Cast<ObjectId>().Select(id => id.Database.TransactionManager.TopTransaction.GetObject(id, OpenMode.ForRead)).Cast<AttributeReference>()
                                .FirstOrDefault(ar => ar.Tag.Equals(tag,StringComparison.CurrentCultureIgnoreCase));

      if (attribute == null)
      {
        throw Error.KeyNotFound(tag);
      }
      else
      {
        attribute.UpgradeOpen();
          attribute.TextString = value;
      }
    }
}
}
`
Thanks,
DaSnodgrass

**Comment by sanzoghenzo** [comment]
Hi,
I just incurred in the same problem, the `AttributeCollection` holds `ObjectId`s, not `AttrubiteReference`s, and the cast is impossible.

Using Autocad2020.

could this be reopened, or should I file a new issue?

**Comment by wtertinek** [comment]
Hi sanzoghenzo,

thanks for raising this issue. Seems that I overlooked DaSnodgrass comment almost three years ago :\

I just pushed a fix, lease give it a try.

Thanks,
Wolfgang

**Comment by sanzoghenzo** [comment]
Just did a quick test, the `SetAttribute` method works! thenk you
