### ISSUE TITLE
Exclude Autocad .NET package from the target

### ISSUE THREAD

**Issue by sanzoghenzo** [wtertinek/Linq2Acad#40]
Hi there! After a year, here I come back at you with another issue 😉 

## Expected Behavior

Building my project that uses Linq2Acad should not copy over the autocad libraries 

## Current Behavior

Compiling my code puts the Autocad libraries into my target directory:

- AcCoreMgd.dll
- ACbMgd.dll
- acdbmgdrep.dll

## Context

This applies to all the versions, but here's mine:

* Linq2Acad Version: 2022 1.0.0
* AutoCAD Version: Autocad 2022

I had the same problem for on of my project that uses the Autocad.NET package directly, and I had to add the following to the PackagereRerence:

```xml
<ExcludeAssets>runtime</ExcludeAssets>
<PrivateAssets>all</PrivateAssets>
```

The key is the `ExcludeAssets`, the `PrivateAsset` shouldn't matter.

### Steps to Reproduce

1. create a new Visual Studio c# library project
3. add Linq2Acad from nuget
4. build the solution
5. the autocad dlls are in the output folder

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information for the team

**Comment by wtertinek** [comment]
Hi sanzoghenzo, nice to hear from you again. :) Thanks for raising this issue, I'll take care of it.

**Comment by wtertinek** [comment]
I'm trying to solve this one too before creating a new release, but for whatever reason it won't work. No matter which combination of `ExcludeAssets` and `PrivateAssets` I use, I still get the AutoCAD assemblies in the output directory. Any ideas?

**Comment by wtertinek** [comment]
When I compile the Linq2Acad project alone, the references are not copied (as expected). When I create a Nuget package and add it to a test project, the AutoCAD assemblies suddenly are back again. I guess I have to add something in the nuspec files.

**Comment by wtertinek** [comment]
OK, found it. The `exclude="runtime"` has to be added to the nuspec as well.

I created RC-packages for all versions. Would be great if you give it a try and verify if the two issues you raised are fixed. Thx!

**Comment by sanzoghenzo** [comment]
It works! thanks a lot for taking a look at this.
