### ISSUE TITLE
AcadDatabase.OpenForEdit not saving on exit anymore

### ISSUE THREAD

**Issue by sanzoghenzo** [wtertinek/Linq2Acad#49]
Hi there! Here I am with another round...

Could it be that [this commit](https://github.com/wtertinek/Linq2Acad/commit/27a2e36c786ee5d2a2759f0c2e1bef2d2b10639c) broke the ability to save the drawing when using AcadDatabase.OpenForEdit?

## Expected Behavior

This should save the edits made:

```cs
using (var db = AcadDatabase.OpenForEdit(path))
{
  someActionsThatModifiesTheDrawing(db);
}
```

## Current Behavior

It doesn't save the drawing. I still see the old version.

Using the debugger, I see that [this constructor](https://github.com/wtertinek/Linq2Acad/blob/f8dcab331e6e42c13011f9a2f7596ef6c2885a4d/src/Linq2Acad/AcadDatabase.cs#L27-L34) is called, and results in `saveOnCommit` to be false because  `saveAsFileName` is not yet populated (it is on the following line).

## Context

* Linq2Acad Version: 2022 v1.0.0
* AutoCAD Version: 2022/2023

## Failure Information

No failures, it just sets saveOnCommit to false and thus it doesn't call the `Database.SaveAs` method during Dispose.

### Sample Code

see above

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information for the team

**Comment by wtertinek** [comment]
Hi sanzoghenzo,

yes, you are right. The error is in line 30:

```csharp
saveOnCommit = saveAsFileName != null;
```

should be

```csharp
saveOnCommit = outFileName != null;
```

or the constructor argument `outFileName` could be renamed to `saveAsFileName`.

I'll provide a fix ASAP.

Thanks,
Wolfgang
