### ISSUE TITLE
add accoreconsole compatibility

### ISSUE THREAD

**Issue by sanzoghenzo** [wtertinek/Linq2Acad#7]
Hi, thanks a ton for this great library!

I would like to use it for some automation with accoreconsole, the headless autocad.

To be able to work with the console, an autocad plugin needs to ditch the AcMgd.dll reference.

It seems that Linq2Acad can support this simply by removing the reference and use 

`using Autodesk.AutoCAD.ApplicationServices.Core;`

in `AcadDatabase.cs`.

**Comment by wtertinek** [comment]
Hi, thanks for raising this issue and providing the solution. I didn't realize that it doesn't work with the core console.

I just updated the project files, they now only reference AutoCAD.NET.Core and I changed the _using_ in _AcadDatabase.cs_ as you described it.

Please test if it now works for you.

Thanks for your participation!

**Comment by wtertinek** [comment]
@sanzoghenzo, did you have success using it with Core Console? If so, you can close this issue. Thanks.

**Comment by sanzoghenzo** [comment]
I finally had the chance to test it, still working out the best way to debug things in AcCoreConsole... 

It does work! Thank you!
